apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: linkerd-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host:
    http:
      paths:
      - path: /linkerd
        backend:
          serviceName: linkerd-web
          servicePort: http

