apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: linkerd-web-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    #nginx.ingress.kubernetes.io/rewrite-target: /$1
    #nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  rules:
  - host:
    http:
      paths:
      - path: 
        backend:
          serviceName: linkerd-web
          servicePort: http

