apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-apps-sync
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: argo-apps
    repoURL: git@github.com:Kassadd/test-k8s.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
