
repo: git@github.com:Kassadd/test-k8s.git
targetRevision: master
appsPath: argo-apps

argo-cd:
    installCRDs: false
    dex:
        enabled: false
    server:
        ingress:
            enabled: false
        config:
            repositories: |
                - url: git@github.com:Kassadd/test-k8s.git
                  sshPrivateKeySecret:
                    name: argocd-secret
                    key: repo.sshprivatekey
        extraArgs:
            insecure: true
    configs:
        argocdServerAdminPassword: $2y$12$vUmoDfoeEEqvP2Z1H5nNGeiVm75h7z9.lqVSvVP1Rz1JEHOmBJHs6
   