# Default values for commons.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
namePrefix: pro-
nameSuffix: ""
nameOverride: test2
fullnameOverride: test2
fullnamePrefix: pro-
fullnameSuffix: ""
fullnameOverride: test2

image_repository: docker
image_tag: "19.03.5-dind"
image_pullPolicy: IfNotPresent

replicaCount: 2

container:
  containerPort: 80
  namePort: http

  livenessProbe:
    initialDelaySeconds: 30
    path: /
    port: 80
  
  readinessProbe:
    initialDelaySeconds: 30
    path: /
    port: 80

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

service:
  enabled: true
  type: ClusterIP
