# Default values for commons.
# This is a YAML-formatted file.
# Declare name/value pairs to be passed into your templates.
namePrefix: dev-
fullnamePrefix: dev-

#Dummy
image_repository: busybox
image_tag: "1"
image_pullPolicy: IfNotPresent
##

replicaCount: 2

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 1
  targetCPUUtilizationPercentage: 50
  targetMemoryUtilizationPercentage: 60

nodeSelector:
  kubernetes.io/os: linux
  intent: apps

tolerations:
- key: "workload"
  operator: "Equal"
  value: "app"
  effect: "NoSchedule"  

container:
  containerPort: 80
  namePort: http

  livenessProbe:
    initialDelaySeconds: 30
    path: /
    port: 80
  
  readinessProbe:
    initialDelaySeconds: 30
    path: /
    port: 80

  resources:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

service:
  enabled: true
  type: ClusterIP

  ports:
  - name: http
    port: 80
    targetPort: http
  # - name: https
  #   port: https
  #   targetPort: https

ingress:
  enabled: true
  domain: javirp.com
  public: false
  annotations: 
    snginx.ingress.kubernetes.io/rewrite-target: "/$1"
  #subdomain: none
  path: /
  backend:
    servicePort: http
