prometheus-operator:
    alertmanager:
        ingress: 
            enabled: true
            annotations:
                nginx.ingress.kubernetes.io/rewrite-target: /$1
                kubernetes.io/ingress.class: nginx-public
            hosts:
            - prometheus.javirp.com
            paths:
            - /alert

    grafana:
        ingress:
            enabled: true
            annotations:
                nginx.ingress.kubernetes.io/rewrite-target: /$1
                kubernetes.io/ingress.class: nginx-public
            hosts:
            - prometheus.javirp.com
            paths:
            - /grafana

    prometheus:
        ingress:
            enabled: true
            annotations:
                nginx.ingress.kubernetes.io/rewrite-target: /$1
                kubernetes.io/ingress.class: nginx-public
            hosts:
            - prometheus.javirp.com
            paths:
            - /            