external-dns:
    image:
        registry: "registry.opensource.zalan.do"
        repository: teapot/external-dns
        tag: v0.5.17

    aws:
        region: "" #Same node
        zoneType: private

    policy: sync
    sources:
    - ingress

    provider: aws

    interval: "1m"
    registry: "txt"
    txtOwnerId: "managedEKS-private"
    annotationFilter: "kubernetes.io/ingress.class=nginx-private"
    domainFilters:
        - javirp.com
    

