fluentd-elasticsearch:

  awsSigningSidecar:
    enabled: true

  elasticsearch:
    host: "search-test-cluster-2mvag5xft2n6w7bq45seazhz6y.eu-west-1.es.amazonaws.com"
    port: 443
    scheme: "https"

  extraConfigMaps:
    filters.conf: |-
      <filter kubernetes.**>
          @type grep
          <exclude>
              key $['kubernetes']['namespace_name']
              pattern "argocd"
          </exclude>
      </filter>