apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx
    server: https://kubernetes.default.svc
  project: system-project
  source:
    path: cluster-setup/ingress-nginx
    repoURL: git@github.com:Kassadd/test-k8s.git
    targetRevision: HEAD