# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: argocd
#   namespace: {{ .Values.global.argocd_ns }}
# spec:
#   destination:
#     namespace: argocd
#     server: {{ .Values.global.server.cluster }}
#   project: {{ .Values.project }}
#   source:
#     path: "{{ .Values.repo_path }}/argocd"
#     repoURL: {{ .Values.global.git.repo }}
#     targetRevision: {{ .Values.global.targetRevision }}