apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Values.argocd_ns }}
spec:
  destination:
    namespace: ingress-nginx
    server: {{ .Values.server.cluster }}
  project: {{ .Values.project }}
  source:
    path: cluster-setup/ingress-nginx
    repoURL: {{ .Values.git.repo }}
    targetRevision: {{ .Values.targetRevision }}   