apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: {{ .Values.global.argocd_ns }}
spec:
  destination:
    namespace: linkerd
    server: {{ .Values.global.server.cluster }}
  project: {{ .Values.project }}
  source:
    path: "{{ .Values.repo_path }}/linkerd"
    repoURL: {{ .Values.global.git.repo }}
    targetRevision: {{ .Values.global.targetRevision }}