apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: {{ .Values.project }}
  namespace: {{ .Values.argocd_ns }}
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-2"
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  description: 'system'
  destinations:
  - namespace: kube-system
    server: {{ .Values.server.cluster }}
  - namespace: linkerd
    server: {{ .Values.server.cluster}}
  - namespace: argocd
    server: {{ .Values.server.cluster }}
  - namespace: kubernetes-dashboard
    server: {{ .Values.server.cluster }}
  - namespace: ingress-nginx
    server: {{ .Values.server.cluster }}
  orphanedResources:
    warn: false
  sourceRepos:
  - {{ .Values.git.repo }}
