apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: filebeat
  namespace: {{ .Values.global.argocd_ns }}
spec:
  destination:
    namespace: kube-system
    server: {{ .Values.global.server.cluster }}
  project: {{ .Values.project }}
  source:
    path: "{{ .Values.repo_path }}/filebeat"
    repoURL: {{ .Values.global.git.repo }}
    targetRevision: {{ .Values.global.targetRevision }}
#  syncPolicy:
#    automated:
#      prune: true
#      selfHeal: true