apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: linkerd
  namespace: {{ .Values.argocd_ns }}
spec:
  destination:
    namespace: linkerd
    server: {{ .Values.server.cluster }}
  project: {{ .Values.project }}
  source:
    path: cluster-setup/linkerd
    repoURL: {{ .Values.git.repo }}
    targetRevision: {{ .Values.targetRevision }}