apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-public
  namespace: {{ .Values.global.argocd_ns }}
spec:
  destination:
    namespace: ingress-nginx
    server: {{ .Values.global.server.cluster }}
  project: {{ .Values.project }}
  source:
    path: "{{ .Values.repo_path }}/ingress-nginx-public"
    repoURL: {{ .Values.global.git.repo }}
    targetRevision: {{ .Values.global.targetRevision }}
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true
  