apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: elasticSearch
  namespace: {{ .Values.global.argocd_ns }}
spec:
  destination:
    namespace: external
    server: {{ .Values.global.server.cluster }}
  project: {{ .Values.project }}
  source:
    path: "{{ .Values.repo_path }}/elasticSearch"
    repoURL: {{ .Values.global.git.repo }}
    targetRevision: {{ .Values.global.targetRevision }}