apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: {{ .Values.global.argocd_ns }}
spec:
  destination:
    namespace: ingress-nginx
    server: {{ .Values.global.server.cluster }}
  project: {{ .Values.project }}
  source:
    path: "{{ .Values.repo_path }}/ingress-nginx"
    repoURL: {{ .Values.global.git.repo }}
    targetRevision: {{ .Values.global.targetRevision }}
  # syncPolicy:
  #   automated:
  #     prune: true
  #     selfHeal: true

---

apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    app.kubernetes.io/part-of: ingress-nginx
  annotations:
    linkerd.io/inject: disabled
    "helm.sh/hook": pre-install