apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: argocd
  annotations:
    linkerd.io/inject: enabled
#    "helm.sh/hook": pre-install


