publicDomain: &publicDomain javirp.com

nginx-ingress:
    controller:
        ingressClass: nginx-private

        publishService:
            enabled: true

        nodeSelector:
            kubernetes.io/os: linux
            intent: apps
        
        tolerations:
            - key: "workload"
              operator: "Equal"
              value: "app"
              effect: "NoSchedule"    

        config:
            use-forwarded-headers: "true"
#            proxy-real-ip-cidr: "0.0.0.0/0" # restrict this to the IP addresses of ELB
            use-proxy-protocol: "true"
            hsts: "true"
            hsts-include-subdomains: "true"
            hsts-preload: "true"
            http-snippet: |
                server {
                    listen 8080 proxy_protocol;
                    server_tokens off;
                    return 301 https://$host$request_uri;
                }

        containerPort:
            http: 80
            http-redirect: 8080

        autoscaling:
            enabled: false
            minReplicas: 2
            maxReplicas: 4
            targetCPUUtilizationPercentage: 30
            targetMemoryUtilizationPercentage: 30
        
        service:
            annotations:
                # replace with the correct value of the generated certificate in the AWS console
                service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:eu-west-1:044827916946:certificate/9d61140c-1060-4f16-b111-b1e661cd3308"
                # the backend instances are HTTP
                service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "tcp"
                # Map port 443
                service.beta.kubernetes.io/aws-load-balancer-ssl-ports: https
                # Ensure the ELB idle timeout is less than nginx keep-alive timeout. By default,
                # NGINX keep-alive is set to 75s. If using WebSockets, the value will need to be
                # increased to '3600' to avoid any potential issues.
                service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "60"
                # by default the type is elb (classic load balancer).
                service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
                service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: '*'

            ports:
                http: 80
                https: 443

            targetPorts:
                http: http-redirect
                https: http

            externalTrafficPolicy: "Cluster"

    defaultBackend:
        nodeSelector:
            kubernetes.io/os: linux
            intent: apps     
        tolerations:
            - key: "workload"
              operator: "Equal"
              value: "app"
              effect: "NoSchedule"    

external-dns:
    image:
        registry: "registry.opensource.zalan.do"
        repository: teapot/external-dns
        tag: v0.5.17

    aws:
        region: "" #Same node
        zoneType: private

    policy: sync
    sources:
        - ingress

    provider: aws

    interval: "1m"
    registry: "txt"
    txtOwnerId: "managedEKS-private"
    annotationFilter: "kubernetes.io/ingress.class=nginx-private"
    domainFilters:
        - *publicDomain