dependencies:
- name: nginx-ingress
  Version: 1.27.0   
  repository: https://kubernetes-charts.storage.googleapis.com/
- name: external-dns
  Version: 2.13.1  
  repository: https://kubernetes-charts.storage.googleapis.com/