{{- template "common.deployment" (list . "mychart.deployment") -}}
{{- define "mychart.deployment" -}}
## Define overrides for your Deployment resource here, e.g.
spec:
  replicas: {{ required "Required .Values.replicaCount" .Values.replicaCount }}
  template:
    spec:
      containers:
      - {{ template "common.container" (list . "mychart.deployment.container") }}
{{- end -}}

{{- define "mychart.deployment.container" -}}
ports:
- containerPort: {{ .Values.container.containerPort }}
  name: {{ .Values.container.namePort }}
livenessProbe:
  initialDelaySeconds: {{ .Values.container.livenessProbe.initialDelaySeconds }}
  httpGet:
    path: {{ .Values.container.livenessProbe.path }}
    port: {{ .Values.container.livenessProbe.port }}
readinessProbe:
  initialDelaySeconds: {{ .Values.container.readinessProbe.initialDelaySeconds }}
  httpGet:
    path: {{ .Values.container.readinessProbe.path }}
    port: {{ .Values.container.readinessProbe.port }}
resources:
  limits:
    cpu: {{ .Values.container.resources.limits.cpu }}
    memory: {{ .Values.container.resources.limits.memory }}
  requests:
    cpu: {{ .Values.container.resources.requests.cpu }}
    memory: {{ .Values.container.resources.requests.memory }}

envFrom:
- configMapRef:
    name: {{ template "common.fullname" . }}

{{- end -}}
