filebeat:
  
  image: "docker.elastic.co/beats/filebeat-oss"

  filebeatConfig:
    filebeat.yml: |
      
      setup.ilm.enabled: false

      filebeat.inputs:
      - type: container
        paths: 
          - '/var/lib/docker/containers/*/*.log'
        format: docker
        processors:
        - add_kubernetes_metadata: ~
        - drop_event:
            when:
              equals:
                kubernetes.namespace: "monitoring"

      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
        protocol: "https"
        index: "k8s-%{[kubernetes][namespace]}-%{+yyyy.MM.dd}" 
      
      setup.template.name: "k8s-"
      setup.template.pattern: "k8s-*"
      setup.template.overwrite: true

  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "app"
      effect: "NoSchedule" 

  extraEnvs:
      - name: ELASTICSEARCH_HOSTS
        value: search-test-cluster-2mvag5xft2n6w7bq45seazhz6y.eu-west-1.es.amazonaws.com:443