filebeat:
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "app"
      effect: "NoSchedule" 

  extraEnvs:
      - name: ELASTICSEARCH_HOSTS
        value: search-test-cluster-2mvag5xft2n6w7bq45seazhz6y.eu-west-1.es.amazonaws.com:443