filebeat:
  
  image: "docker.elastic.co/beats/filebeat-oss"

  filebeatConfig:
    filebeat.yml: |
      
      setup.ilm.enabled = false

      filebeat.inputs:
      - type: docker
        containers.ids:
        - '*'
        processors:
        - add_kubernetes_metadata: ~
      
      output.elasticsearch:
        host: '${NODE_NAME}'
        hosts: '${ELASTICSEARCH_HOSTS:elasticsearch-master:9200}'
        compression_level: 6      
        index: "%{[fields.kubernetes.namespace]}-%{+yyyy.MM.dd}" 


  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "app"
      effect: "NoSchedule" 

  extraEnvs:
      - name: ELASTICSEARCH_HOSTS
        value: search-test-cluster-2mvag5xft2n6w7bq45seazhz6y.eu-west-1.es.amazonaws.com:443
        protocol: "https"