apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubeseal
  namespace: argocd
spec:
  destination:
    namespace: kube-system
    server: https://kubernetes.default.svc
  project: system-project
  source:
    path: cluster-setup/kubeseal
    repoURL: git@github.com:Kassadd/test-k8s.git
    targetRevision: HEAD